name: 🦍 Despliegue

on:
  push:
    branches: [main]

  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    name: 🐘 Desplegar
    runs-on: ubuntu-latest

    steps:
      - name: 🐯 Obtener código del repositorio
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.DOMINIO_AZURE }}
          username: ${{ secrets.USUARIO_AZURE }}
          key: ${{ secrets.LLAVE_SSH }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd ${{ secrets.RUTA }}
            git pull origin main
            nvm install
            nvm use
            corepack enable
            yarn install --immutable
            yarn build
