name: 🐾 Estilo Código

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: 🐯 Obtener código del repositorio
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: 🐜 Activar Corepack
        run: corepack enable

      - name: 🐝 Usar Node
        uses: actions/setup-node@v7
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: 🦒 Instalar dependencias
        run: |
          yarn install --immutable

      - name: 👀 Buscar errores
        run: yarn lint

      - name: 🔎 Revisar tipos y construir el sitio
        run: yarn build
